#!/bin/bash
CONNECTIONS=$1
REPLICAS=$2
go build --tags "static netgo" -o client client.go
for (( c=0; c<${REPLICAS}; c++ ))
do
    docker run -v $(pwd)/client:/client alpine /client ${CONNECTIONS} &
done
